name: '游냍 Report de Bug'
description: Cria um ticket para um bug encontrado.
title: '游냍 [BUG] - <titulo>'
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: 'Descri칞칚o'
      description: Descri칞칚o do seu issue
      placeholder: Ao realizar '...' opera칞칚o
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: 'Passos para reprodu칞칚o'
      description: Descri칞칚o dos passos para reprodu칞칚o
      value: |
        1. V치 para '...'
        2. Clique em '....'
        3. Chame a API '....'
        4. Veja o erro
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: 'Evid칡ncias'
      description: Se aplicavel, adicione imagens para enriquecer o troubleshoot.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 'Logs'
      description: Se aplicavel, providencie alguns logs para enriquecer o troubleshoot. Ser치 automaticamente renderizado como c칩digo-fonte, sem necessidade de cr치se tripla.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: 'Navegadores'
      description: Em qual navegador foi poss칤vel verificar o erro?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: 'SO'
      description: Qual o sistema operacional?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
