export { CgTab } from 'react-icons/cg';
export { FaPause, FaPlay, FaTree, FaUser } from 'react-icons/fa';
export {
  AlertFillIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleSlashIcon,
  CommentDiscussionIcon,
  CommentIcon,
  EyeClosedIcon,
  EyeIcon,
  FoldIcon,
  GearIcon,
  HomeIcon,
  KebabHorizontalIcon,
  LinkExternalIcon,
  LinkIcon,
  ListUnorderedIcon,
  MoonIcon,
  PencilIcon,
  PersonIcon,
  PlusIcon,
  SearchIcon,
  SignOutIcon,
  SquareFillIcon,
  SunIcon,
  ThreeBarsIcon,
  TrashIcon,
  UnfoldIcon,
  XCircleFillIcon,
} from '@primer/octicons-react';
