#!/bin/sh

RELATIVE_SCRIPT_DIR="$(dirname "$0")"
RELATIVE_SCRIPT_PATH="$(dirname "$0")/$(basename "$0")"
DEST_DIARY_DIR="${RELATIVE_SCRIPT_DIR}/../pages/init/diary"
MATCH_FILES_NAMES="????-??-??*.md"
IGNORE_LITERAL='**Próximo capítulo:**'


build_readme() {
    destination_file="$1"
    first_line="$2"
    sort_flag="$3"

    # Header
    cat >"${destination_file}" <<EOF
<!---
This file was autogenerated by ${RELATIVE_SCRIPT_PATH} on $(TZ=UTC date +"%Y-%d-%m %H:%M %Z").
You may update this file by creating another file and running ${RELATIVE_SCRIPT_PATH}.
Do NOT edit this file manually, every changes WILL be overridden.
--->

# tabnews.com.br

${first_line}

## Índice de entradas

EOF

    # TOC
    for entry in $(find "${DEST_DIARY_DIR}" -name "${MATCH_FILES_NAMES}" | sort "${sort_flag}") ; do
        echo "- [$(head -n1 "${entry}" | cut -d ' ' -f2-)]($( basename "${entry}" ))" >> "${destination_file}"
    done

    # Text in between
    cat >> "${destination_file}" <<EOF

## Diário

EOF

    # Content
    for entry in $(find "${DEST_DIARY_DIR}" -name "${MATCH_FILES_NAMES}" | sort "${sort_flag}") ; do
        grep -Fv "${IGNORE_LITERAL}" "${entry}" >> "${destination_file}"
    done
}


build_readme "${DEST_DIARY_DIR}/README.md" 'Ver diário na ordem cronológica [aqui](./README-chronological.md)!' "-r"
build_readme "${DEST_DIARY_DIR}/README-chronological.md" 'Ver diário com entradas mais recentes [aqui](./README.md)!' "-d"
